// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ShopOrder struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	OrderDate   pgtype.Timestamptz `db:"order_date" json:"order_date"`
	TotalAmount pgtype.Numeric     `db:"total_amount" json:"total_amount"`
}

type ShopOrderProduct struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	OrderID   pgtype.UUID `db:"order_id" json:"order_id"`
	ProductID pgtype.UUID `db:"product_id" json:"product_id"`
}

type ShopProduct struct {
	ID    pgtype.UUID    `db:"id" json:"id"`
	Name  *string        `db:"name" json:"name"`
	Price pgtype.Numeric `db:"price" json:"price"`
}

type ShopUser struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	Name     *string     `db:"name" json:"name"`
	Email    *string     `db:"email" json:"email"`
	Password *string     `db:"password" json:"password"`
}
