// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ChangeEmailUser(ctx context.Context, arg ChangeEmailUserParams) (*ChangeEmailUserRow, error)
	ChangePriceProduct(ctx context.Context, arg ChangePriceProductParams) (*ShopProduct, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (*ShopOrder, error)
	CreateOrderProducts(ctx context.Context, arg CreateOrderProductsParams) (*ShopOrderProduct, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (*CreateProductRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*CreateUserRow, error)
	DeleteOrder(ctx context.Context, id pgtype.UUID) (*ShopOrder, error)
	DeleteOrderProducts(ctx context.Context, orderID pgtype.UUID) (*ShopOrderProduct, error)
	DeleteProduct(ctx context.Context, name *string) (*DeleteProductRow, error)
	DeleteUser(ctx context.Context, name *string) (*DeleteUserRow, error)
	GetProduct(ctx context.Context, name *string) (*ShopProduct, error)
	GetProducts(ctx context.Context) ([]*ShopProduct, error)
	GetUser(ctx context.Context, name *string) (*ShopUser, error)
	GetUserStatistics(ctx context.Context, name *string) (*GetUserStatisticsRow, error)
	GetUsers(ctx context.Context) ([]*ShopUser, error)
	GetUsersOrders(ctx context.Context) ([]*GetUsersOrdersRow, error)
}

var _ Querier = (*Queries)(nil)
