version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    environment:
      - ENV=development
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: OnlineShop
    volumes:
      - ./conf_postgres/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
